# These are vendored in as a quick hack from 
# https://github.com/aspect-build/bazel-lib/tree/main/lib
# It would be better to depend on them directly, or see if there is a more wrapped
# way to allow invokation of both windows and linux binaries
